### ISSUE TITLE
request for release to melodic 

### ISSUE THREAD

**Issue by k-okada** [ros-gbp/navigation_tutorials-release#1]
@wjwwood could you mind releasing into melodic? since we are successfully released gmapping to melodic, we're now able to release navigation_tutorials!

**Comment by wjwwood** [comment]
I don't have time, but I can give someone the power.

We can continue to chat here, but I'm going to close the issue.

**Comment by k-okada** [comment]
@wjwwood if you agreed to set this package to orphaned, I can release this.

**Comment by wjwwood** [comment]
Well, I can just release it I guess. I need to work on it for Noetic anyways.

**Comment by wjwwood** [comment]
https://github.com/ros/rosdistro/pull/22592

**Comment by k-okada** [comment]
thank you!
--
◉ Kei Okada



2019年10月8日(火) 3:55 William Woodall <notifications@github.com>:
